name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  fetch-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: install dependencies
      run: npm install

    - name: cache node modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: cached_node_modules_${{ hashFiles('**/package-lock.json') }}
        restore-keys: cached_node_modules_

  lint:
    runs-on: ubuntu-latest
    needs: fetch-dependencies
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_

    - name: lint ts
      run: npm run lint:ts

    - name: lint hbs
      run: npm run lint:hbs

    - name: lint scss
      run: npm run lint:scss

  test:
    runs-on: ubuntu-latest
    needs: fetch-dependencies
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v2
    - id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: cached_node_modules_${{ hashFiles('**/yarn.lock') }}
        restore-keys: cached_node_modules_

      - name: run tests
        run: npm run test:ember