name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - master

defaults:
  run:
    working-directory: frontend

jobs:
  fetch-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: install dependencies
      run: |
        npm install
        yarn install

  lint:
    runs-on: ubuntu-latest
    needs: fetch-dependencies
    steps:
    - name: lint ts
      run: yarn lint:ts

    - name: lint hbs
      run: yarn lint:hbs

    - name: lint scss
      run: yarn lint:scss

  test:
    runs-on: ubuntu-latest
    needs: fetch-dependencies
    steps:
      - name: run tests
        run: yarn test