name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: install dependencies
      run: npm install

    - name: lint ts
      run: npm run lint:ts

    - name: lint hbs
      run: npm run lint:hbs

    - name: lint scss
      run: npm run lint:scss

    - name: run tests
      run: npm run test:ember